services:
  - type: redis
    name: btc-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0

  - type: web
    name: btc-backend
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_DATA_REDIS_HOST
        fromService:
          type: redis
          name: btc-redis
          property: host
      - key: SPRING_DATA_REDIS_PORT
        fromService:
          type: redis
          name: btc-redis
          property: port
      - key: CORS_ALLOWED_ORIGINS
        value: https://btc-frontend.onrender.com

  - type: web
    name: btc-frontend
    plan: free
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://btc-backend.onrender.com
